[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"

[context.deploy-preview]
  command = "yarn build-preview"

# Redirect default Netlify subdomain to primary domain
https://zeromileedutech.netlify.com/* https://zeromileedutech.com/:splat 301!
